// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using anyfood_dotnet;

#nullable disable

namespace anyfood_dotnet.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20251019161434_cat")]
    partial class cat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("anyfood_dotnet.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Фрукти"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Овочі"
                        },
                        new
                        {
                            Id = 3,
                            Name = "М'ясо"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Риба"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Крупи"
                        });
                });

            modelBuilder.Entity("anyfood_dotnet.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 52.0,
                            Carbs = 14.0,
                            CategoryId = 1,
                            Fat = 0.20000000000000001,
                            ImageUrl = "",
                            Name = "Яблуко",
                            Protein = 0.29999999999999999
                        },
                        new
                        {
                            Id = 2,
                            Calories = 89.0,
                            Carbs = 23.0,
                            CategoryId = 1,
                            Fat = 0.29999999999999999,
                            ImageUrl = "",
                            Name = "Банан",
                            Protein = 1.1000000000000001
                        },
                        new
                        {
                            Id = 3,
                            Calories = 165.0,
                            Carbs = 0.0,
                            CategoryId = 3,
                            Fat = 3.6000000000000001,
                            ImageUrl = "",
                            Name = "Куряча грудка",
                            Protein = 31.0
                        },
                        new
                        {
                            Id = 4,
                            Calories = 208.0,
                            Carbs = 0.0,
                            CategoryId = 4,
                            Fat = 13.0,
                            ImageUrl = "",
                            Name = "Лосось",
                            Protein = 20.0
                        },
                        new
                        {
                            Id = 5,
                            Calories = 55.0,
                            Carbs = 11.0,
                            CategoryId = 2,
                            Fat = 0.59999999999999998,
                            ImageUrl = "",
                            Name = "Броколі",
                            Protein = 3.7000000000000002
                        },
                        new
                        {
                            Id = 6,
                            Calories = 130.0,
                            Carbs = 28.0,
                            CategoryId = 5,
                            Fat = 0.29999999999999999,
                            ImageUrl = "",
                            Name = "Рис білий",
                            Protein = 2.7000000000000002
                        },
                        new
                        {
                            Id = 7,
                            Calories = 160.0,
                            Carbs = 9.0,
                            CategoryId = 1,
                            Fat = 15.0,
                            ImageUrl = "",
                            Name = "Авокадо",
                            Protein = 2.0
                        });
                });

            modelBuilder.Entity("anyfood_dotnet.Models.Food", b =>
                {
                    b.HasOne("anyfood_dotnet.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("anyfood_dotnet.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
